name: Gradle Package

on:
  push:
    branches:
      - '**'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Display bradle version
      run: ./gradlew versionDisplay

    - name: Display version File
      run: ./gradlew versionFile

    - name: Build Image and EBArchive
      run: ./gradlew build buildImage buildEBArchive
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Export VERSION_TAG
      run: cat build/version.properties | grep VERSION_TAG >> $GITHUB_ENV

    - name: Publish to AWS ECR
      if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew publishImage
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to EB
      if: startsWith(github.ref, 'refs/tags/')
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: QuickPrint
        region: ap-southeast-2
        version_label: "${{ env.VERSION_TAG  }}"
        deployment_package: build/distributions/eb.zip
        existing_bucket_name: quickprint-eb-deployments
        wait_for_deployment: false
